site_name: aiothrottles
site_url: https://konstantintogoi.github.io/aiothrottles
repo_url: https://github.com/KonstantinTogoi/aiothrottles
repo_name: aiothrottles
nav:
  - 'Home': index.md
  - 'Getting Started': getting_started.md
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences